version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file template.yml --s3-bucket photos-2402 --output-template-file packaged-template.yml
artifacts:
  type: zip
  files:
    - template.yml
    - packaged-template.yml